/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceDentista;

import java.awt.GridBagLayout;

/**
 *
 * @author NAILSON
 */
public class ApresentacaoSistema extends javax.swing.JPanel {
 GridBagLayout layout = new GridBagLayout();

    /**
     * Creates new form ApresentacaoSistema
     */
    public ApresentacaoSistema() {
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Professor: Pedro kislansky ");
        add(jLabel2);
        jLabel2.setBounds(100, 240, 260, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Marca-Salvador-SITE2_copy_6.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(60, 10, 370, 140);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sistema desenvolvido por Felipe Alves e Nailson Melo");
        add(jLabel4);
        jLabel4.setBounds(6, 160, 474, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sistema de Clinica Odontologica");
        add(jLabel5);
        jLabel5.setBounds(80, 290, 290, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Atividade da matéria Programação II");
        add(jLabel6);
        jLabel6.setBounds(60, 200, 340, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/fundoapre.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 490, 380);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
