package InterfaceDentista;


import Persistencia.BancoFuncionario;
import Persistencia.ConexaoBD;
import Negocio.ModeloFuncionario;
import Negocio.ModeloTabeladen;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NAILSON
 */
public class TelaFuncionario extends javax.swing.JFrame {

    ModeloFuncionario fun = new ModeloFuncionario();
    BancoFuncionario banco = new BancoFuncionario();
    ConexaoBD conec = new ConexaoBD();
    int flag=0;
    
    public TelaFuncionario() {
        initComponents();
        preencherTabela("select *from bdfuncionario order by codigo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelarfuncionario = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pesquisarfuncionario = new javax.swing.JButton();
        alterarfuncionario = new javax.swing.JButton();
        excluirfuncionario = new javax.swing.JButton();
        salvarfuncionario = new javax.swing.JButton();
        novofuncionario = new javax.swing.JButton();
        jFormattedemailfuncionario = new javax.swing.JFormattedTextField();
        jFormattedtelefonefuncionario = new javax.swing.JFormattedTextField();
        usuariofuncionario = new javax.swing.JTextField();
        endfuncionario = new javax.swing.JTextField();
        codigofuncionario = new javax.swing.JTextField();
        cidadefuncionario = new javax.swing.JTextField();
        senhafuncionario = new javax.swing.JPasswordField();
        jFormattedcepfuncionario = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxfuncaofuncionario = new javax.swing.JComboBox<>();
        nomefuncionario = new javax.swing.JTextField();
        jFormattedcpffuncionario = new javax.swing.JFormattedTextField();
        jComboBoxuffuncionario = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxsexofuncionario = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        bairrofuncionario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pesquisafuncionario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelafuncionario = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tela de Funcionario");
        setResizable(false);
        getContentPane().setLayout(null);

        cancelarfuncionario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancelarfuncionario.setText("Cancelar");
        cancelarfuncionario.setEnabled(false);
        cancelarfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarfuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarfuncionario);
        cancelarfuncionario.setBounds(230, 370, 100, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Fechar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(560, 370, 100, 30);

        pesquisarfuncionario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pesquisarfuncionario.setText("Pesquisar");
        pesquisarfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarfuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(pesquisarfuncionario);
        pesquisarfuncionario.setBounds(10, 220, 110, 30);

        alterarfuncionario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        alterarfuncionario.setText("Alterar");
        alterarfuncionario.setEnabled(false);
        alterarfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarfuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(alterarfuncionario);
        alterarfuncionario.setBounds(340, 370, 100, 30);

        excluirfuncionario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        excluirfuncionario.setText("Excluir");
        excluirfuncionario.setEnabled(false);
        excluirfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirfuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(excluirfuncionario);
        excluirfuncionario.setBounds(450, 370, 100, 30);

        salvarfuncionario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        salvarfuncionario.setText("Salvar");
        salvarfuncionario.setEnabled(false);
        salvarfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarfuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(salvarfuncionario);
        salvarfuncionario.setBounds(120, 370, 100, 30);

        novofuncionario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        novofuncionario.setText("Novo");
        novofuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novofuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(novofuncionario);
        novofuncionario.setBounds(10, 370, 100, 30);

        jFormattedemailfuncionario.setEnabled(false);
        jFormattedemailfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedemailfuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedemailfuncionario);
        jFormattedemailfuncionario.setBounds(390, 110, 270, 30);

        try {
            jFormattedtelefonefuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedtelefonefuncionario.setEnabled(false);
        getContentPane().add(jFormattedtelefonefuncionario);
        jFormattedtelefonefuncionario.setBounds(390, 60, 130, 30);

        usuariofuncionario.setEnabled(false);
        getContentPane().add(usuariofuncionario);
        usuariofuncionario.setBounds(390, 210, 130, 30);

        endfuncionario.setEnabled(false);
        endfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endfuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(endfuncionario);
        endfuncionario.setBounds(90, 110, 290, 30);

        codigofuncionario.setEnabled(false);
        getContentPane().add(codigofuncionario);
        codigofuncionario.setBounds(10, 60, 70, 30);

        cidadefuncionario.setEnabled(false);
        cidadefuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadefuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(cidadefuncionario);
        cidadefuncionario.setBounds(300, 160, 140, 30);

        senhafuncionario.setEnabled(false);
        getContentPane().add(senhafuncionario);
        senhafuncionario.setBounds(530, 210, 130, 30);

        try {
            jFormattedcepfuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedcepfuncionario.setEnabled(false);
        jFormattedcepfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedcepfuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedcepfuncionario);
        jFormattedcepfuncionario.setBounds(10, 160, 120, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Senha:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(530, 190, 60, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Função:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(520, 130, 110, 40);

        jComboBoxfuncaofuncionario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxfuncaofuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "DENTISTA", "RECEPCIONISTA", " " }));
        jComboBoxfuncaofuncionario.setEnabled(false);
        getContentPane().add(jComboBoxfuncaofuncionario);
        jComboBoxfuncaofuncionario.setBounds(520, 160, 140, 30);

        nomefuncionario.setEnabled(false);
        getContentPane().add(nomefuncionario);
        nomefuncionario.setBounds(90, 60, 290, 30);

        try {
            jFormattedcpffuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedcpffuncionario.setEnabled(false);
        jFormattedcpffuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedcpffuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedcpffuncionario);
        jFormattedcpffuncionario.setBounds(530, 60, 130, 30);

        jComboBoxuffuncionario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxuffuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UF", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO", " " }));
        jComboBoxuffuncionario.setEnabled(false);
        getContentPane().add(jComboBoxuffuncionario);
        jComboBoxuffuncionario.setBounds(450, 160, 60, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Usuario:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(390, 180, 70, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("UF");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(450, 140, 50, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Cep:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 130, 40, 40);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Sexo:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 80, 50, 40);

        jComboBoxsexofuncionario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxsexofuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jComboBoxsexofuncionario.setEnabled(false);
        getContentPane().add(jComboBoxsexofuncionario);
        jComboBoxsexofuncionario.setBounds(10, 110, 70, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Bairro:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(140, 140, 80, 20);

        bairrofuncionario.setEnabled(false);
        bairrofuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairrofuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(bairrofuncionario);
        bairrofuncionario.setBounds(140, 160, 150, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Cidade:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(300, 130, 90, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("E-mail:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(390, 80, 90, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Endereço:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 90, 150, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Cpf:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(530, 40, 60, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Telefone:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(390, 40, 70, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nome:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 40, 60, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Codigo:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 40, 50, 20);

        pesquisafuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisafuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(pesquisafuncionario);
        pesquisafuncionario.setBounds(120, 220, 240, 30);

        tabelafuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Cpf", "Telefone", "Endereço", "E-mail"
            }
        ));
        tabelafuncionario.getTableHeader().setReorderingAllowed(false);
        tabelafuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelafuncionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelafuncionario);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 250, 650, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/fundo_vida_1.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 110, 670, 310);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/fundo_vida_1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 670, 320);

        setSize(new java.awt.Dimension(675, 436));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void alterarfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarfuncionarioActionPerformed
        flag=2;
        nomefuncionario.setEnabled(true);
        jFormattedtelefonefuncionario.setEnabled(true);
        jFormattedcpffuncionario.setEnabled(true);
        endfuncionario.setEnabled(true);
        bairrofuncionario.setEnabled(true);
        cidadefuncionario.setEnabled(true);
        jFormattedcepfuncionario.setEnabled(true);
        jComboBoxuffuncionario.setEnabled(true);
        jComboBoxsexofuncionario.setEnabled(true);
        jFormattedemailfuncionario.setEnabled(true);
        jComboBoxfuncaofuncionario.setEnabled(true);
        usuariofuncionario.setEnabled(true);
        senhafuncionario.setEnabled(true);
        salvarfuncionario.setEnabled(true);
        cancelarfuncionario.setEnabled(true);
        alterarfuncionario.setEnabled(false);
        excluirfuncionario.setEnabled(false);
        pesquisafuncionario.setEnabled(false);
        pesquisarfuncionario.setEnabled(false);
        novofuncionario.setEnabled(false);
        
        preencherTabela("select * from bdfuncionario order by codigo");
    }//GEN-LAST:event_alterarfuncionarioActionPerformed

    private void excluirfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirfuncionarioActionPerformed
       int resposta = 0;
       resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir cadastro?");
       if(resposta==JOptionPane.YES_OPTION){
           fun.setCodigo(Integer.parseInt(codigofuncionario.getText()));
           banco.Excluir(fun);
           codigofuncionario.setText("");
           nomefuncionario.setText("");
           jFormattedtelefonefuncionario.setText("");
           jFormattedcpffuncionario.setText("");
           endfuncionario.setText("");
           bairrofuncionario.setText("");
           cidadefuncionario.setText("");
           jFormattedcepfuncionario.setText("");
           jFormattedemailfuncionario.setText("");
           usuariofuncionario.setText("");
           senhafuncionario.setText("");
           nomefuncionario.setEnabled(false);
           jFormattedtelefonefuncionario.setEnabled(false);
           jFormattedcpffuncionario.setEnabled(false);
           endfuncionario.setEnabled(false);
           bairrofuncionario.setEnabled(false);
           cidadefuncionario.setEnabled(false);
           jFormattedcepfuncionario.setEnabled(false);
           jComboBoxuffuncionario.setEnabled(false);
           jComboBoxsexofuncionario.setEnabled(false);
           jFormattedemailfuncionario.setEnabled(false);
           jComboBoxfuncaofuncionario.setEnabled(false);
           usuariofuncionario.setEnabled(false);
           senhafuncionario.setEnabled(false);
           salvarfuncionario.setEnabled(false);
           pesquisafuncionario.setEnabled(true);
           pesquisarfuncionario.setEnabled(true);
           alterarfuncionario.setEnabled(false);
           excluirfuncionario.setEnabled(false);
           preencherTabela("select *from bdfuncionario order by codigo");
           
       }
    }//GEN-LAST:event_excluirfuncionarioActionPerformed

    private void pesquisafuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisafuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisafuncionarioActionPerformed

    private void endfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endfuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endfuncionarioActionPerformed

    private void jFormattedemailfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedemailfuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedemailfuncionarioActionPerformed

    private void cidadefuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadefuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadefuncionarioActionPerformed

    private void jFormattedcepfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedcepfuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedcepfuncionarioActionPerformed

    private void jFormattedcpffuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedcpffuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedcpffuncionarioActionPerformed

    private void novofuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novofuncionarioActionPerformed
        flag=1;
        nomefuncionario.setEnabled(true);
        jFormattedtelefonefuncionario.setEnabled(true);
        jFormattedcpffuncionario.setEnabled(true);
        endfuncionario.setEnabled(true);
        bairrofuncionario.setEnabled(true);
        cidadefuncionario.setEnabled(true);
        jFormattedcepfuncionario.setEnabled(true);
        jComboBoxuffuncionario.setEnabled(true);
        jComboBoxsexofuncionario.setEnabled(true);
        jFormattedemailfuncionario.setEnabled(true);
        jComboBoxfuncaofuncionario.setEnabled(true);
        usuariofuncionario.setEnabled(true);
        senhafuncionario.setEnabled(true);
        salvarfuncionario.setEnabled(true);
        cancelarfuncionario.setEnabled(true);
        pesquisafuncionario.setEnabled(false);
        pesquisarfuncionario.setEnabled(false);
        codigofuncionario.setText("");
        nomefuncionario.setText("");
        jFormattedtelefonefuncionario.setText("");
        jFormattedcpffuncionario.setText("");
        endfuncionario.setText("");
        bairrofuncionario.setText("");
        cidadefuncionario.setText("");
        jFormattedcepfuncionario.setText("");
        jFormattedemailfuncionario.setText("");
        usuariofuncionario.setText("");
        senhafuncionario.setText("");
    }//GEN-LAST:event_novofuncionarioActionPerformed

    private void salvarfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarfuncionarioActionPerformed
        if(nomefuncionario.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Nome do funcionario é obrigatório!!!");
           nomefuncionario.requestFocus();
       }else if(jFormattedtelefonefuncionario.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "Telefone do funcionario é obrigatório!!!");
          jFormattedtelefonefuncionario.requestFocus();
       }else if(jFormattedcpffuncionario.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "Cpf do funcionario é obrigatório!!!");
          jFormattedcpffuncionario.requestFocus();
       }else if(endfuncionario.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "Endereço do funcionario é obrigatório!!!");
          endfuncionario.requestFocus();
       }else if(cidadefuncionario.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "Cidade do funcionario é obrigatório!!!");
          cidadefuncionario.requestFocus();
       }else if(jFormattedcepfuncionario.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "Cep do funcionario é obrigatório!!!");
          jFormattedcepfuncionario.requestFocus();
       }else if(jFormattedemailfuncionario.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "Email do funcionario é obrigatório!!!");
          jFormattedemailfuncionario.requestFocus();
       }else if(usuariofuncionario.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "Usuario do funcionario é obrigatório para ter acesso ao sistema!!!");
          usuariofuncionario.requestFocus();
       }else if(senhafuncionario.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "Senha do funcionario é obrigatório!!!");
          senhafuncionario.requestFocus();
       }else if(bairrofuncionario.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "Bairro do funcionario é obrigatório!!!");
          bairrofuncionario.requestFocus();
           
       }else
                
        if(flag==1){
       fun.setNome(nomefuncionario.getText());
       fun.setTelefone(jFormattedtelefonefuncionario.getText());
       fun.setCpf(jFormattedcpffuncionario.getText());
       fun.setEndereco(endfuncionario.getText());
       fun.setBairro(bairrofuncionario.getText());
       fun.setCidade(cidadefuncionario.getText());
       fun.setCep(jFormattedcepfuncionario.getText());
       fun.setUf((String)jComboBoxuffuncionario.getSelectedItem());
       fun.setSexo((String)jComboBoxsexofuncionario.getSelectedItem());
       fun.setEmail(jFormattedemailfuncionario.getText());
       fun.setFuncao((String)jComboBoxfuncaofuncionario.getSelectedItem());
       fun.setUsuario(usuariofuncionario.getText());
       fun.setSenha(senhafuncionario.getText());
       banco.salvar(fun);
       nomefuncionario.setText("");
       jFormattedtelefonefuncionario.setText("");
       jFormattedcpffuncionario.setText("");
       endfuncionario.setText("");
       bairrofuncionario.setText("");
       cidadefuncionario.setText("");
       jFormattedcepfuncionario.setText("");
       jFormattedemailfuncionario.setText("");
       usuariofuncionario.setText("");
       senhafuncionario.setText("");
       nomefuncionario.setEnabled(false);
       jFormattedtelefonefuncionario.setEnabled(false);
       jFormattedcpffuncionario.setEnabled(false);
       endfuncionario.setEnabled(false);
       bairrofuncionario.setEnabled(false);
       cidadefuncionario.setEnabled(false);
       jFormattedcepfuncionario.setEnabled(false);
       jComboBoxuffuncionario.setEnabled(false);
       jComboBoxsexofuncionario.setEnabled(false);
       jFormattedemailfuncionario.setEnabled(false);
       jComboBoxfuncaofuncionario.setEnabled(false);
       usuariofuncionario.setEnabled(false);
       senhafuncionario.setEnabled(false);
       salvarfuncionario.setEnabled(false);
       pesquisafuncionario.setEnabled(true);
       pesquisarfuncionario.setEnabled(true);
       cancelarfuncionario.setEnabled(false);
       preencherTabela("select *from bdfuncionario order by codigo");
       }else{
       fun.setCodigo((Integer.parseInt(codigofuncionario.getText())));
       fun.setNome(nomefuncionario.getText());
       fun.setTelefone(jFormattedtelefonefuncionario.getText());
       fun.setCpf(jFormattedcpffuncionario.getText());
       fun.setEndereco(endfuncionario.getText());
       fun.setBairro(bairrofuncionario.getText());
       fun.setCidade(cidadefuncionario.getText());
       fun.setCep(jFormattedcepfuncionario.getText());
       fun.setUf((String)jComboBoxuffuncionario.getSelectedItem());
       fun.setSexo((String)jComboBoxsexofuncionario.getSelectedItem());
       fun.setEmail(jFormattedemailfuncionario.getText());
       fun.setFuncao((String)jComboBoxfuncaofuncionario.getSelectedItem());
       fun.setUsuario(usuariofuncionario.getText());
       fun.setSenha(senhafuncionario.getText());
       
       banco.Editar(fun);
       codigofuncionario.setText("");
       nomefuncionario.setText("");
       jFormattedtelefonefuncionario.setText("");
       jFormattedcpffuncionario.setText("");
       endfuncionario.setText("");
       bairrofuncionario.setText("");
       cidadefuncionario.setText("");
       jFormattedcepfuncionario.setText("");
       jFormattedemailfuncionario.setText("");
       usuariofuncionario.setText("");
       senhafuncionario.setText("");
       nomefuncionario.setEnabled(false);
       jFormattedtelefonefuncionario.setEnabled(false);
       jFormattedcpffuncionario.setEnabled(false);
       endfuncionario.setEnabled(false);
       bairrofuncionario.setEnabled(false);
       cidadefuncionario.setEnabled(false);
       jFormattedcepfuncionario.setEnabled(false);
       jComboBoxuffuncionario.setEnabled(false);
       jComboBoxsexofuncionario.setEnabled(false);
       jFormattedemailfuncionario.setEnabled(false);
       jComboBoxfuncaofuncionario.setEnabled(false);
       usuariofuncionario.setEnabled(false);
       senhafuncionario.setEnabled(false);
       salvarfuncionario.setEnabled(false);
       novofuncionario.setEnabled(true);
       cancelarfuncionario.setEnabled(false);
       pesquisarfuncionario.setEnabled(true);
       pesquisafuncionario.setEnabled(true);
       preencherTabela("select *from bdfuncionario order by codigo");
      
      }
    }//GEN-LAST:event_salvarfuncionarioActionPerformed

    private void cancelarfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarfuncionarioActionPerformed
        nomefuncionario.setEnabled(!true);
        jFormattedtelefonefuncionario.setEnabled(!true);
        jFormattedcpffuncionario.setEnabled(!true);
        endfuncionario.setEnabled(!true);
        bairrofuncionario.setEnabled(!true);
        cidadefuncionario.setEnabled(!true);
        jFormattedcepfuncionario.setEnabled(!true);
        jComboBoxuffuncionario.setEnabled(!true);
        jComboBoxsexofuncionario.setEnabled(!true);
        jFormattedemailfuncionario.setEnabled(!true);
        jComboBoxfuncaofuncionario.setEnabled(!true);
        usuariofuncionario.setEnabled(!true);
        senhafuncionario.setEnabled(!true);
       salvarfuncionario.setEnabled(!true);
       cancelarfuncionario.setEnabled(!true);
       novofuncionario.setEnabled(true);
       alterarfuncionario.setEnabled(false);
       excluirfuncionario.setEnabled(false);
       pesquisafuncionario.setEnabled(true);
       pesquisarfuncionario.setEnabled(true);
    }//GEN-LAST:event_cancelarfuncionarioActionPerformed

    private void pesquisarfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarfuncionarioActionPerformed
        fun.setPesquisa(pesquisafuncionario.getText());
        ModeloFuncionario modelo = banco.buscaFuncionario(fun);
        codigofuncionario.setText(String.valueOf(modelo.getCodigo()));
        nomefuncionario.setText(modelo.getNome());
        jFormattedtelefonefuncionario.setText(modelo.getTelefone());
        jFormattedcpffuncionario.setText(modelo.getCpf());
        endfuncionario.setText(modelo.getEndereco());
        bairrofuncionario.setText(modelo.getBairro());
        cidadefuncionario.setText(modelo.getCidade());
        jFormattedcepfuncionario.setText(modelo.getCep());
        jComboBoxuffuncionario.setSelectedItem(modelo.getUf());
        jComboBoxsexofuncionario.setSelectedItem(modelo.getSexo());
        jFormattedemailfuncionario.setText(modelo.getEmail());
        jComboBoxfuncaofuncionario.setSelectedItem(modelo.getFuncao());
        usuariofuncionario.setText(modelo.getUsuario());
        senhafuncionario.setText(modelo.getSenha());
        alterarfuncionario.setEnabled(true);
        excluirfuncionario.setEnabled(true);
        alterarfuncionario.setEnabled(false);
        excluirfuncionario.setEnabled(false);
       preencherTabela("select * from bdfuncionario where nome like'%"+fun.getPesquisa()+"%'");
    }//GEN-LAST:event_pesquisarfuncionarioActionPerformed

    private void tabelafuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelafuncionarioMouseClicked
       String nome =""+tabelafuncionario.getValueAt(tabelafuncionario.getSelectedRow(), 1);
        conec.conexao();
        conec.executaSql("select * from bdfuncionario where nome='"+nome+"'");
        try {
            conec.rs.first();
            codigofuncionario.setText(String.valueOf(conec.rs.getInt("codigo")));
            nomefuncionario.setText(conec.rs.getString("nome"));
            jFormattedtelefonefuncionario.setText(conec.rs.getString("telefone"));
            jFormattedcpffuncionario.setText(conec.rs.getString("cpf"));
            endfuncionario.setText(conec.rs.getString("endereco"));
            bairrofuncionario.setText(conec.rs.getString("bairro"));
           cidadefuncionario.setText(conec.rs.getString("cidade"));
            jFormattedcepfuncionario.setText(conec.rs.getString("cep"));
            jComboBoxuffuncionario.setSelectedItem(conec.rs.getString("uf"));
            jComboBoxsexofuncionario.setSelectedItem(conec.rs.getString("sexo"));
            jFormattedemailfuncionario.setText(conec.rs.getString("email"));
            jComboBoxfuncaofuncionario.setSelectedItem(conec.rs.getString("funcao"));
            usuariofuncionario.setText(conec.rs.getString("usuario"));
            senhafuncionario.setText(conec.rs.getString("senha"));
            alterarfuncionario.setEnabled(true);
            excluirfuncionario.setEnabled(true);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Impossivel selecionar dados do Funcionario!!!\n Erro"+ex.getMessage());
        }
        
        conec.desconectar();
                                    
    }//GEN-LAST:event_tabelafuncionarioMouseClicked

    private void bairrofuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairrofuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bairrofuncionarioActionPerformed

    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"Codigo","Nome","Telefone","Cpf","Endereço","E-mail"};
        conec.conexao();
        conec.executaSql(Sql);
        
        try{
         conec.rs.first();
         do{
             
          dados.add(new Object[]{conec.rs.getInt("codigo"),conec.rs.getString("nome"),conec.rs.getString("telefone"),conec.rs.getString("cpf"),conec.rs.getString("endereco"),conec.rs.getString("email")});
         
         }while(conec.rs.next());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane,"Tabela de Funcionario sem registro");
        }
            ModeloTabeladen tabela = new ModeloTabeladen(dados,colunas);
            
            tabelafuncionario.setModel(tabela);
            tabelafuncionario.getColumnModel().getColumn(0).setPreferredWidth(50);
            tabelafuncionario.getColumnModel().getColumn(0).setResizable(false);
            tabelafuncionario.getColumnModel().getColumn(1).setPreferredWidth(160);
            tabelafuncionario.getColumnModel().getColumn(1).setResizable(false);
            tabelafuncionario.getColumnModel().getColumn(2).setPreferredWidth(95);
            tabelafuncionario.getColumnModel().getColumn(2).setResizable(false);
            tabelafuncionario.getColumnModel().getColumn(3).setPreferredWidth(100);
            tabelafuncionario.getColumnModel().getColumn(3).setResizable(false);
            tabelafuncionario.getColumnModel().getColumn(4).setPreferredWidth(160);
            tabelafuncionario.getColumnModel().getColumn(4).setResizable(false);
            tabelafuncionario.getColumnModel().getColumn(5).setPreferredWidth(150);
            tabelafuncionario.getColumnModel().getColumn(5).setResizable(false);
            tabelafuncionario.getTableHeader().setReorderingAllowed(false);
            tabelafuncionario.setAutoResizeMode(tabelafuncionario.AUTO_RESIZE_OFF);
            tabelafuncionario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            
        conec.desconectar();
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarfuncionario;
    private javax.swing.JTextField bairrofuncionario;
    private javax.swing.JButton cancelarfuncionario;
    private javax.swing.JTextField cidadefuncionario;
    private javax.swing.JTextField codigofuncionario;
    private javax.swing.JTextField endfuncionario;
    private javax.swing.JButton excluirfuncionario;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBoxfuncaofuncionario;
    private javax.swing.JComboBox<String> jComboBoxsexofuncionario;
    private javax.swing.JComboBox<String> jComboBoxuffuncionario;
    private javax.swing.JFormattedTextField jFormattedcepfuncionario;
    private javax.swing.JFormattedTextField jFormattedcpffuncionario;
    private javax.swing.JFormattedTextField jFormattedemailfuncionario;
    private javax.swing.JFormattedTextField jFormattedtelefonefuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomefuncionario;
    private javax.swing.JButton novofuncionario;
    private javax.swing.JTextField pesquisafuncionario;
    private javax.swing.JButton pesquisarfuncionario;
    private javax.swing.JButton salvarfuncionario;
    private javax.swing.JPasswordField senhafuncionario;
    private javax.swing.JTable tabelafuncionario;
    private javax.swing.JTextField usuariofuncionario;
    // End of variables declaration//GEN-END:variables
}
